.travis.yml
(cherry picked from commit ac918cb483428f9e03b22cf057ce068336812520)
#13
=> add -U option terasolunaorg/terasoluna-tourreservation#170

terasoluna-tourreservation-domain/pom.xml, terasoluna-tourreservation-domain/src/main/java/org/terasoluna/tourreservation/domain/service/reserve/ReserveServiceImpl.java, terasoluna-tourreservation-domain/src/main/java/org/terasoluna/tourreservation/domain/service/tourinfo/TourInfoSharedServiceImpl.java, terasoluna-tourreservation-domain/src/main/resources/META-INF/spring/tourreservation-domain.xml, terasoluna-tourreservation-domain/src/test/java/org/terasoluna/tourreservation/domain/service/reserve/ReserveServiceImplTest.java, terasoluna-tourreservation-domain/src/test/java/org/terasoluna/tourreservation/domain/service/tourinfo/TourInfoServiceImplTest.java, terasoluna-tourreservation-domain/src/test/java/org/terasoluna/tourreservation/domain/service/tourinfo/TourInfoSharedServiceImplTest.java, terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/TourSearchValidateTest.java, terasoluna-tourreservation-web/src/main/java/org/terasoluna/tourreservation/app/managereservation/ReportingHelper.java, terasoluna-tourreservation-web/src/main/java/org/terasoluna/tourreservation/app/searchtour/DepYearCodeList.java, terasoluna-tourreservation-web/src/main/java/org/terasoluna/tourreservation/app/searchtour/SearchTourController.java, terasoluna-tourreservation-web/src/test/java/org/terasoluna/tourreservation/app/searchtour/SearchTourControllerTest.java
manually merged from https://github.com/terasolunaorg/terasoluna-tourreservation/commit/8790583fbb1389d6d55bda06747be8871377c8e0
Please review terasolunaorg/terasoluna-tourreservation#168
=> Modified to use JodataTimeDateFactory terasolunaorg/terasoluna-tourreservation#168

terasoluna-tourreservation-domain/pom.xml, terasoluna-tourreservation-env/pom.xml, terasoluna-tourreservation-initdb/pom.xml, terasoluna-tourreservation-parent/pom.xml, terasoluna-tourreservation-selenium/pom.xml, terasoluna-tourreservation-web/pom.xml
(cherry picked from commit ad62f362bd6bf37fdf144fc4777fff290e672adb)
please review terasolunaorg/terasoluna-tourreservation#166
=> reversion 1.1.0 -> 5.0.0 terasolunaorg/terasoluna-tourreservation#166

terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/TourSearchValidateTest.java
(cherry picked from commit b5abcdcfb0811760f6677048ceff99858309b1b2)
backport from jpa/master.
Please review terasolunaorg/terasoluna-tourreservation#177, and merge to master branch.
=> Setted size of window terasolunaorg/terasoluna-tourreservation#177

terasoluna-tourreservation-domain/src/test/java/org/terasoluna/tourreservation/domain/repository/tourinfo/TourInfoRepositoryImplTest.java
(cherry picked from commit 1cc5998ca7a1e181079e528d64c723211e1a2a86)
backport from jpa/master.
Please review terasolunaorg/terasoluna-tourreservation#179, and merge to master branch.
=> Changed to past date terasolunaorg/terasoluna-tourreservation#179

terasoluna-tourreservation-web/src/main/resources/ValidationMessages.properties
(cherry picked from commit 06532fd522958e36d34053f0207d3aedaf435e14)
backport from jpa/master
Please review terasolunaorg/terasoluna-tourreservation#176, and merge to master branch.
=> Added ValidationMessages.properties

terasoluna-tourreservation-domain/src/main/java/org/terasoluna/tourreservation/domain/repository/customer/CustomerRepository.java, terasoluna-tourreservation-domain/src/main/java/org/terasoluna/tourreservation/domain/repository/reserve/ReserveRepository.java, terasoluna-tourreservation-domain/src/main/java/org/terasoluna/tourreservation/domain/repository/tourinfo/TourInfoRepository.java, terasoluna-tourreservation-domain/src/main/java/org/terasoluna/tourreservation/domain/service/customer/CustomerServiceImpl.java, terasoluna-tourreservation-domain/src/main/java/org/terasoluna/tourreservation/domain/service/reserve/ReserveService.java, terasoluna-tourreservation-domain/src/main/java/org/terasoluna/tourreservation/domain/service/reserve/ReserveServiceImpl.java, terasoluna-tourreservation-domain/src/main/java/org/terasoluna/tourreservation/domain/service/tourinfo/TourInfoSharedService.java, terasoluna-tourreservation-domain/src/main/java/org/terasoluna/tourreservation/domain/service/tourinfo/TourInfoSharedServiceImpl.java, terasoluna-tourreservation-domain/src/main/resources/org/terasoluna/tourreservation/domain/repository/customer/CustomerRepository.xml, terasoluna-tourreservation-domain/src/main/resources/org/terasoluna/tourreservation/domain/repository/reserve/ReserveRepository.xml, terasoluna-tourreservation-domain/src/main/resources/org/terasoluna/tourreservation/domain/repository/tourinfo/TourInfoRepository.xml, terasoluna-tourreservation-domain/src/test/java/org/terasoluna/tourreservation/domain/repository/reserve/ReserveRepositoryImplTest.java, terasoluna-tourreservation-domain/src/test/java/org/terasoluna/tourreservation/domain/service/customer/CustomerServiceImplTest.java, terasoluna-tourreservation-domain/src/test/java/org/terasoluna/tourreservation/domain/service/reserve/ReserveServiceImplTest.java, terasoluna-tourreservation-domain/src/test/java/org/terasoluna/tourreservation/domain/service/tourinfo/TourInfoSharedServiceImplTest.java, terasoluna-tourreservation-web/src/main/java/org/terasoluna/tourreservation/app/managereservation/ManageReservationController.java, terasoluna-tourreservation-web/src/main/java/org/terasoluna/tourreservation/app/managereservation/ManageReservationHelper.java, terasoluna-tourreservation-web/src/main/java/org/terasoluna/tourreservation/app/reservetour/ReserveTourHelper.java, terasoluna-tourreservation-web/src/test/java/org/terasoluna/tourreservation/app/managereservation/ManageReservationControllerTest.java, terasoluna-tourreservation-web/src/test/java/org/terasoluna/tourreservation/app/managereservation/ManageReservationHelperTest.java, terasoluna-tourreservation-web/src/test/java/org/terasoluna/tourreservation/app/reservetour/ReserveTourHelperTest.java
Please review terasolunaorg/terasoluna-tourreservation-mybatis3#2, and merge to master branch.
=> Mybatis3 edition refactoring

terasoluna-tourreservation-domain/pom.xml, terasoluna-tourreservation-env/pom.xml, terasoluna-tourreservation-initdb/pom.xml, terasoluna-tourreservation-parent/pom.xml, terasoluna-tourreservation-selenium/pom.xml, terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/LogInReservUpdateTest.java, terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/TokenCheckErrorTest.java, terasoluna-tourreservation-web/pom.xml
(cherry picked from commit e3979f1849eb8b66bfff99dd543ee3b7463caa85)
backport from jpa/master.
Please review terasolunaorg/terasoluna-tourreservation#188, and merge to master branch.
=> Changed framework name terasolunaorg/terasoluna-tourreservation#188

terasoluna-tourreservation-domain/pom.xml, terasoluna-tourreservation-parent/pom.xml, terasoluna-tourreservation-selenium/pom.xml, terasoluna-tourreservation-web/pom.xml
(cherry picked from commit 452eb0c0beb4fec88243235e97194d8cf1b62ffb)
backport from jpa/master.
Please review terasolunaorg/terasoluna-tourreservation#191, and merge to master branch.
=> Set scope(test,provided) terasolunaorg/terasoluna-tourreservation#191

README.md
=> Update README.md for 5.x. #30

README.md
(cherry picked from commit dc20771a26e65db1ae8a041cac85a8b516096d3f)
Please review #30 .
=> [5.0.x] Update README.md for 5.x. #30

terasoluna-tourreservation-domain/pom.xml, terasoluna-tourreservation-env/pom.xml, terasoluna-tourreservation-initdb/pom.xml, terasoluna-tourreservation-parent/pom.xml, terasoluna-tourreservation-selenium/pom.xml, terasoluna-tourreservation-web/pom.xml
(cherry picked from commit d089d77959a8b473804744eaf80b5482b85011b0)
please review [#203](https://github.com/terasolunaorg/terasoluna-tourreservation/issues/203)
=> Upgrade Version to 5.1.0-SNAPSHOT. #203

terasoluna-tourreservation-domain/pom.xml, terasoluna-tourreservation-env/pom.xml, terasoluna-tourreservation-initdb/pom.xml, terasoluna-tourreservation-parent/pom.xml, terasoluna-tourreservation-selenium/pom.xml, terasoluna-tourreservation-web/pom.xml
(cherry picked from commit 61557830020501e3a613243ae2fced4fe6dc8897)
please review [#204](https://github.com/terasolunaorg/terasoluna-tourreservation/issues/204)
=> Upgrade Version to 5.0.1-SNAPSHOT. #204

.gitignore
(cherry picked from commit 7a241e74bb30ef0692a6de4191d1c8844a97e2c7)
Please review terasolunaorg/terasoluna-tourreservation#220 .
=> Ignore IDEA project file. terasolunaorg/terasoluna-tourreservation#220

terasoluna-tourreservation-domain/src/main/java/org/terasoluna/tourreservation/domain/service/userdetails/ReservationUserDetailsService.java
(cherry picked from commit 359da1746f869265b0cacaf0d9643bc91ee66c07)
Please review terasolunaorg/terasoluna-tourreservation#174 .
=> Remove todo for UsernameNotFoundException's message. terasolunaorg/terasoluna-tourreservation#174

terasoluna-tourreservation-domain/src/main/java/org/terasoluna/tourreservation/domain/service/userdetails/ReservationUserDetailsService.java
(cherry picked from commit 359da1746f869265b0cacaf0d9643bc91ee66c07)
(cherry picked from commit 39a05d40b178de76e042b2f03ca2f5d31d1e44cc)
Please review terasolunaorg/terasoluna-tourreservation#174 .
=> [5.0.x] Remove todo for UsernameNotFoundException's message. terasolunaorg/terasoluna-tourreservation#174

.travis.yml
(cherry picked from commit 72990e8308ef570f8cdc6d8054f29c96bac7b230)
Please review terasolunaorg/terasoluna-tourreservation#222 .
=> Support JDK8 on travis. terasolunaorg/terasoluna-tourreservation#222

terasoluna-tourreservation-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml, terasoluna-tourreservation-env/configs/tomcat8-postgresql/resources/META-INF/spring/tourreservation-codelist.properties, terasoluna-tourreservation-env/configs/tomcat8-postgresql/resources/META-INF/spring/tourreservation-env.xml, terasoluna-tourreservation-env/configs/tomcat8-postgresql/resources/META-INF/spring/tourreservation-infra.properties, terasoluna-tourreservation-env/configs/tomcat8-postgresql/resources/logback.xml, terasoluna-tourreservation-env/pom.xml
(cherry picked from commit 82ca3cd6bc802a779d6ccd2aecc03fa4b623dc83)
Please review terasolunaorg/terasoluna-tourreservation#214 .
=> Support tomcat8 terasolunaorg/terasoluna-tourreservation#214

terasoluna-tourreservation-web/src/main/webapp/WEB-INF/views/common/error/not-found-error.jsp, terasoluna-tourreservation-web/src/main/webapp/WEB-INF/web.xml
(cherry picked from commit 99457148dbd6238aa77cfb4818c1e55c4b36a939)
Please review terasolunaorg/terasoluna-tourreservation#94 .
=> Add not found page. terasolunaorg/terasoluna-tourreservation#94

.travis.yml
(cherry picked from commit 72990e8308ef570f8cdc6d8054f29c96bac7b230)
(cherry picked from commit 026c6bf38b54e7bccc0b3689ad0913c94db6e6bf)
Please review terasolunaorg/terasoluna-tourreservation#222 .
=> [5.0.x] Support JDK8 on travis. terasolunaorg/terasoluna-tourreservation#222

terasoluna-tourreservation-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml, terasoluna-tourreservation-env/configs/tomcat8-postgresql/resources/META-INF/spring/tourreservation-codelist.properties, terasoluna-tourreservation-env/configs/tomcat8-postgresql/resources/META-INF/spring/tourreservation-env.xml, terasoluna-tourreservation-env/configs/tomcat8-postgresql/resources/META-INF/spring/tourreservation-infra.properties, terasoluna-tourreservation-env/configs/tomcat8-postgresql/resources/logback.xml, terasoluna-tourreservation-env/pom.xml
(cherry picked from commit 82ca3cd6bc802a779d6ccd2aecc03fa4b623dc83)
(cherry picked from commit 4b3dd38af12018c89781f758deaeeeadab102269)
Please review terasolunaorg/terasoluna-tourreservation#214 .
=> [5.0.x] Support tomcat8 terasolunaorg/terasoluna-tourreservation#214

terasoluna-tourreservation-domain/pom.xml, terasoluna-tourreservation-env/pom.xml, terasoluna-tourreservation-parent/pom.xml, terasoluna-tourreservation-selenium/pom.xml, terasoluna-tourreservation-web/pom.xml
(cherry picked from commit b638ffc7e5a1648e61f844e2bf3a0f66a2edef8c)
Please review terasolunaorg/terasoluna-tourreservation#212 .
=> Polish pom.xml. terasolunaorg/terasoluna-tourreservation#212

.travis.yml, terasoluna-tourreservation-initdb/pom.xml
(cherry picked from commit 2481e9d8bd7b1c4e5bf28247c6c3b956696d7789)
Please review terasolunaorg/terasoluna-tourreservation#162 .
=> Fix travis errors terasolunaorg/terasoluna-tourreservation#162

.travis.yml, terasoluna-tourreservation-initdb/pom.xml
(cherry picked from commit 2481e9d8bd7b1c4e5bf28247c6c3b956696d7789)
(cherry picked from commit de26def7efbafdb170b3b934b9b959e511859019)
Please review terasolunaorg/terasoluna-tourreservation#162 .
=> [5.0.x] Fix travis errors terasolunaorg/terasoluna-tourreservation#162

terasoluna-tourreservation-domain/pom.xml, terasoluna-tourreservation-env/pom.xml, terasoluna-tourreservation-initdb/pom.xml, terasoluna-tourreservation-parent/pom.xml, terasoluna-tourreservation-selenium/pom.xml, terasoluna-tourreservation-web/pom.xml
(cherry picked from commit d3b3de601e3946e6de930b1645d90a8d735e3dae)
Please reivew terasolunaorg/terasoluna-tourreservation#240 .
I've changed the commit message(issue no format) by manually.
=> Update to 5.0.2-SNAPSHOT terasolunaorg/terasoluna-tourreservation#240

terasoluna-tourreservation-web/src/main/java/org/terasoluna/tourreservation/app/managereservation/ManageReservationController.java, terasoluna-tourreservation-web/src/main/java/org/terasoluna/tourreservation/app/reservetour/ReserveTourController.java, terasoluna-tourreservation-web/src/test/java/org/terasoluna/tourreservation/app/managereservation/ManageReservationControllerTest.java, terasoluna-tourreservation-web/src/test/java/org/terasoluna/tourreservation/app/reservetour/ReserveTourControllerTest.java
(cherry picked from commit 008a21240e0ccce657a54650dba2e0e77fde9ce5)
Please review terasolunaorg/terasoluna-tourreservation#256.
=> Remove exporting logic of path variable value at the time of redirect. terasolunaorg/terasoluna-tourreservation#256

terasoluna-tourreservation-web/src/main/java/org/terasoluna/tourreservation/app/managereservation/ManageReservationController.java, terasoluna-tourreservation-web/src/main/java/org/terasoluna/tourreservation/app/reservetour/ReserveTourController.java, terasoluna-tourreservation-web/src/test/java/org/terasoluna/tourreservation/app/managereservation/ManageReservationControllerTest.java, terasoluna-tourreservation-web/src/test/java/org/terasoluna/tourreservation/app/reservetour/ReserveTourControllerTest.java
(cherry picked from commit 008a21240e0ccce657a54650dba2e0e77fde9ce5)
(cherry picked from commit aebaff2be29921d016c0c663c5e5089fbbe4d074)
Please review terasolunaorg/terasoluna-tourreservation#256 .
=> [5.0.x] Remove exporting logic of path variable value at the time of redirect. terasolunaorg/terasoluna-tourreservation#256

terasoluna-tourreservation-web/src/main/java/org/terasoluna/tourreservation/app/searchtour/SearchTourController.java, terasoluna-tourreservation-web/src/main/webapp/WEB-INF/views/menu/menu.jsp
(cherry picked from commit c387adbc6805f6c31eb6bde6e2c2eca9e8997cd8)
Please review terasolunaorg/terasoluna-tourreservation#258 .
=> Modify execution timing of SessionStatus#complete. terasolunaorg/terasoluna-tourreservation#258

.travis.yml, terasoluna-tourreservation-parent/pom.xml
(cherry picked from commit cbf4f6349ee164f821cc22d5cc6a7b9667bb2d98)
Please review terasolunaorg/terasoluna-tourreservation#76.
=> #76: Support selenium on travis-CI

.travis.yml, terasoluna-tourreservation-parent/pom.xml
(cherry picked from commit cbf4f6349ee164f821cc22d5cc6a7b9667bb2d98)
(cherry picked from commit fd3080b454641923b0a16bb4f325ca8db610efde)
Please review terasolunaorg/terasoluna-tourreservation#76.
=> [5.0.x] #76: Support selenium on travis-CI

README.md
(cherry picked from commit c485b61f87d45f29e76536d9add19cdf6cc870e0)
Please review terasolunaorg/terasoluna-tourreservation#76.
=> Update 'Deploy war' in README.md terasolunaorg/terasoluna-tourreservation#76

terasoluna-tourreservation-domain/src/main/java/org/terasoluna/tourreservation/domain/service/reserve/AuthorizedReserveSharedService.java, terasoluna-tourreservation-domain/src/main/java/org/terasoluna/tourreservation/domain/service/reserve/AuthorizedReserveSharedServiceImpl.java, terasoluna-tourreservation-domain/src/main/java/org/terasoluna/tourreservation/domain/service/reserve/ReserveServiceImpl.java, terasoluna-tourreservation-domain/src/test/java/org/terasoluna/tourreservation/domain/service/reserve/ReserveServiceImplSecurityTest.java, terasoluna-tourreservation-domain/src/test/java/org/terasoluna/tourreservation/domain/service/reserve/ReserveServiceImplTest.java, terasoluna-tourreservation-domain/src/test/resources/org/terasoluna/tourreservation/domain/service/reserve/ReserveServiceImplSecurityTest-context.xml, terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/UnauthorizedAccessTest.java, terasoluna-tourreservation-web/src/main/resources/META-INF/spring/spring-mvc.xml, terasoluna-tourreservation-web/src/main/resources/META-INF/spring/spring-security.xml
Please review terasolunaorg/terasoluna-tourreservation#213.
**Note:**
I modified the `ReserveServiceImplSecurityTest.java` to apply changes to mybatis3 project.(8393323085807503a30e3a66a3c68a977bae6c76)
=> Implement access control for other owner resource. terasolunaorg/terasoluna-tourreservation#213

terasoluna-tourreservation-domain/src/main/java/org/terasoluna/tourreservation/domain/service/reserve/AuthorizedReserveSharedService.java, terasoluna-tourreservation-domain/src/main/java/org/terasoluna/tourreservation/domain/service/reserve/AuthorizedReserveSharedServiceImpl.java, terasoluna-tourreservation-domain/src/main/java/org/terasoluna/tourreservation/domain/service/reserve/ReserveServiceImpl.java, terasoluna-tourreservation-domain/src/test/java/org/terasoluna/tourreservation/domain/service/reserve/ReserveServiceImplSecurityTest.java, terasoluna-tourreservation-domain/src/test/java/org/terasoluna/tourreservation/domain/service/reserve/ReserveServiceImplTest.java, terasoluna-tourreservation-domain/src/test/resources/org/terasoluna/tourreservation/domain/service/reserve/ReserveServiceImplSecurityTest-context.xml, terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/UnauthorizedAccessTest.java, terasoluna-tourreservation-web/src/main/resources/META-INF/spring/spring-mvc.xml, terasoluna-tourreservation-web/src/main/resources/META-INF/spring/spring-security.xml
Please review terasolunaorg/terasoluna-tourreservation#213.
=> [5.0.x] Implement access control for other owner resource. terasolunaorg/terasoluna-tourreservation#213

.travis.yml
(cherry picked from commit af93d3499bd030256fd9a7ff49f08841d563d218)
Please review terasolunaorg/terasoluna-tourreservation#273.
=> travis-ci migrate to container-based infrastructure. terasolunaorg/terasoluna-tourreservation#273

.travis.yml
(cherry picked from commit af93d3499bd030256fd9a7ff49f08841d563d218)
(cherry picked from commit bedff9614a453e1e6de9eae88bc80d9eb29fbbe7)
Please review terasolunaorg/terasoluna-tourreservation#273.
=> [5.0.x] travis-ci migrate to container-based infrastructure. terasolunaorg/terasoluna-tourreservation#273

.travis.yml
(cherry picked from commit 749a89e84c8f1ab50c83b4275b08e5e4089db305)
Please review terasolunaorg/terasoluna-tourreservation#273.
=> Install latest snapshot of terasoluna-gfw before running build. terasolunaorg/terasoluna-tourreservation#273

.travis.yml
Please review terasolunaorg/terasoluna-tourreservation#273.
=> [5.0.x] Install latest snapshot of terasoluna-gfw before running build. terasolunaorg/terasoluna-tourreservation#273

terasoluna-tourreservation-env/configs/tomcat-postgresql/ContainerConfigXML/context.xml, terasoluna-tourreservation-env/configs/tomcat-postgresql/resources/META-INF/spring/tourreservation-env.xml, terasoluna-tourreservation-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml, terasoluna-tourreservation-env/configs/tomcat8-postgresql/resources/META-INF/spring/tourreservation-env.xml, terasoluna-tourreservation-env/src/main/resources/META-INF/spring/tourreservation-env.xml
changed data source name #102
cherry-pick https://github.com/terasolunaorg/terasoluna-tourreservation/commit/e622e8dc19d414d3ab33d8f9acd51bdd71091982
=> changed data source name #102

terasoluna-tourreservation-domain/src/main/resources/META-INF/mybatis/mybatis-config.xml
Please review terasolunaorg/terasoluna-tourreservation#281.
=> Add defaultFetchSize definition terasolunaorg/terasoluna-tourreservation#281

terasoluna-tourreservation-domain/pom.xml, terasoluna-tourreservation-domain/src/test/java/org/terasoluna/tourreservation/domain/service/reserve/ReserveServiceImplSecurityTest.java
(cherry picked from commit ab87f1ebe17e84b0222cb8b416384f30d1c57fff)
Please review terasolunaorg/terasoluna-tourreservation#287.
=> Modify to use spring-security-test APIs on ReserveServiceImplSecurityTest terasolunaorg/terasoluna-tourreservation#287

terasoluna-tourreservation-web/src/main/webapp/WEB-INF/web.xml
(cherry picked from commit 019220a8eb20d881acb679830f0fcf87b7f2ee93)
(cherry picked from commit 616b63c101c9072d3139e9ee9c67624955a803b3)
Please review terasolunaorg/terasoluna-tourreservation#282.
=> [5.0.x] Add session-config(tracking mode & session timeout) in web.xml terasolunaorg/terasoluna-tourreservation#282

terasoluna-tourreservation-web/src/main/webapp/WEB-INF/web.xml
(cherry picked from commit 019220a8eb20d881acb679830f0fcf87b7f2ee93)
Please review terasolunaorg/terasoluna-tourreservation#282.
=> Add session-config(tracking mode & session timeout) in web.xml terasolunaorg/terasoluna-tourreservation#282

.travis.yml, pom.xml
(cherry picked from commit ed6693ffa643a602ded294313733cac576919e79)
Please review terasolunaorg/terasoluna-tourreservation#295.
=> Update PostgreSQL 9.4 on Travis-CI terasolunaorg/terasoluna-tourreservation#295

terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/common/FunctionTestSupport.java, terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/CustomerRegisterTest.java, terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/CustomerRegisterValidateTest.java, terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/LanguageSwitchTest.java, terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/LogInLogOutTest.java, terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/LogInReservUpdateTest.java, terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/SystemErrorTest.java, terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/TokenCheckErrorTest.java, terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/TourSearchPaginationTest.java, terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/TourSearchRegistValidateTest.java, terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/TourSearchValidateTest.java, terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/UnLogInTourSearchTest.java, terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/UnauthorizedAccessTest.java, terasoluna-tourreservation-selenium/src/test/resources/META-INF/spring/selenium.properties, terasoluna-tourreservation-web/src/main/resources/META-INF/spring/spring-mvc.xml, terasoluna-tourreservation-web/src/main/resources/META-INF/spring/spring-security.xml, terasoluna-tourreservation-web/src/main/webapp/WEB-INF/views/menu/menu.jsp, terasoluna-tourreservation-web/src/main/webapp/WEB-INF/web.xml
(cherry picked from commit 8b232043db3500ea369009497be8dfe0f40b95f0)
Please review terasolunaorg/terasoluna-tourreservation#297.
=> Add functionality to switch a language using UI terasolunaorg/terasoluna-tourreservation#297

.travis.yml, terasoluna-tourreservation-parent/pom.xml
I've backported to 5.0.x, please review terasolunaorg/terasoluna-tourreservation#295.
=> [5.0.x] Update PostgreSQL 9.4 on Travis-CI terasolunaorg/terasoluna-tourreservation#295

terasoluna-tourreservation-domain/src/main/resources/META-INF/mybatis/mybatis-config.xml
I've applied https://github.com/terasolunaorg/terasoluna-tourreservation/issues/281#issuecomment-159796765, please review terasolunaorg/terasoluna-tourreservation#281.
=> Remove proxyFactory from comment area terasolunaorg/terasoluna-tourreservation#281

pom.xml
Please review terasolunaorg/terasoluna-tourreservation#307.
=> Update Tomcat 8.0.29 on Travis-CI terasolunaorg/terasoluna-tourreservation#307

terasoluna-tourreservation-parent/pom.xml
I've backported to 5.0.x, please review terasolunaorg/terasoluna-tourreservation#307.
=> [5.0.x] Update Tomcat 8.0.29 on Travis-CI terasolunaorg/terasoluna-tourreservation#307

terasoluna-tourreservation-initdb/pom.xml
Please review terasolunaorg/terasoluna-tourreservation#303.
=> Remove onError option for sql-maven-plugin terasolunaorg/terasoluna-tourreservation#303

terasoluna-tourreservation-initdb/pom.xml
I've baclported to 5.0.x, please review terasolunaorg/terasoluna-tourreservation#303.
=> [5.0.x] Remove onError option for sql-maven-plugin terasolunaorg/terasoluna-tourreservation#303

pom.xml
Please review terasolunaorg/terasoluna-tourreservation#319.
=> Update Tomcat 8.0.30 on Travis-CI terasolunaorg/terasoluna-tourreservation#319

terasoluna-tourreservation-parent/pom.xml
Please review terasolunaorg/terasoluna-tourreservation#319.
=> [5.0.x] Update Tomcat 8.0.30 on Travis-CI terasolunaorg/terasoluna-tourreservation#319

terasoluna-tourreservation-env/configs/tomcat-postgresql/ContainerConfigXML/context.xml, terasoluna-tourreservation-env/configs/tomcat-postgresql/ContainerConfigXML/context.xml.env.ftl, terasoluna-tourreservation-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml, terasoluna-tourreservation-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml.env.ftl
https://github.com/terasolunaorg/terasoluna-tourreservation/issues/325
https://github.com/terasolunaorg/terasoluna-tourreservation/issues/327
git cherry-pick 0b98c596eb261b066c620908e04e8db4f03b0d6d
git cherry-pick 5795c1b2d35c5702b4f1f300fdccf8b3ac93ff35
=> cherry pick replace tool master

.travis.yml, pom.xml
(cherry picked from commit ff0625b580fb150b28abe7fb4219ed6f721f5a4c)
Please review terasolunaorg/terasoluna-tourreservation#334.
=> Modify to use parent configurations for cargo-maven2-plugin #334

.travis.yml, terasoluna-tourreservation-parent/pom.xml
(cherry picked from commit aca3f37a11b4ea00cebdd625dc99e84165170691)
Please review terasolunaorg/terasoluna-tourreservation#334.
=> [5.0.x] Modify to use parent configurations for cargo-maven2-plugin #334

terasoluna-tourreservation-env/configs/tomcat-postgresql/ContainerConfigXML/context.xml, terasoluna-tourreservation-env/configs/tomcat-postgresql/ContainerConfigXML/context.xml.env.ftl, terasoluna-tourreservation-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml, terasoluna-tourreservation-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml.env.ftl
https://github.com/terasolunaorg/terasoluna-tourreservation/issues/325
https://github.com/terasolunaorg/terasoluna-tourreservation/issues/327
git cherry-pick 0b98c596eb261b066c620908e04e8db4f03b0d6d
git cherry-pick 5795c1b2d35c5702b4f1f300fdccf8b3ac93ff35
=> cherry pick replace tool 5.0.x

terasoluna-tourreservation-domain/src/test/java/org/terasoluna/tourreservation/domain/repository/reserve/ReserveRepositoryImplTest.java
(cherry picked from commit 1e7b8779adf5f197abfd2e21520a1839d88c443d)
Please review terasolunaorg/terasoluna-tourreservation#345.
=> [5.0.x] Fix error of ReserveRepositoryImplTest#testFindByCustomer01 terasolunaorg/terasoluna-tourreservation#345

terasoluna-tourreservation-web/pom.xml
please review [#344](https://github.com/terasolunaorg/terasoluna-tourreservation/issues/344) .
porting to MyBatis3 edition .
=> change dependency web to web-jsp for MyBatis3 edition. issues:#344

terasoluna-tourreservation-domain/src/test/java/org/terasoluna/tourreservation/domain/repository/reserve/ReserveRepositoryImplTest.java
Please review terasolunaorg/terasoluna-tourreservation#345.
=> Fix error of ReserveRepositoryImplTest#testFindByCustomer01 terasolunaorg/terasoluna-tourreservation#345

terasoluna-tourreservation-web/src/main/resources/META-INF/spring/spring-security.xml, terasoluna-tourreservation-web/src/main/webapp/WEB-INF/views/reservetour/reserveForm.jsp
Please review terasolunaorg/terasoluna-tourreservation#343 .
=> #343 Remove RedirectAuthenticationHandler

.travis.yml, pom.xml
Please review terasolunaorg/terasoluna-tourreservation#238 .
=> Update Java version to 1.8 #238

terasoluna-tourreservation-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml, terasoluna-tourreservation-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml.env.ftl
Please review terasolunaorg/terasoluna-tourreservation#338.
=> Fix connection pool settings(maxWaitMillis, maxTotal) for tomcat8 terasolunaorg/terasoluna-tourreservation#338

terasoluna-tourreservation-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml, terasoluna-tourreservation-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml.env.ftl
(cherry picked from commit 8b235c6fc37755fea490408ed64da01c504d5c34)
Please review terasolunaorg/terasoluna-tourreservation#338.
=> [5.0.x] Fix connection pool settings(maxWaitMillis, maxTotal) for tomcat8 terasolunaorg/terasoluna-tourreservation#338

pom.xml
https://github.com/terasolunaorg/terasoluna-tourreservation/issues/354
jdbc postgresql version up 9.4-1206-jdbc41
cherry-pick fcf2bccf74c46478c4ee30ef3307e85d6642180e
=> jdbc postgresql version up 9.4-1206-jdbc41 #354

terasoluna-tourreservation-parent/pom.xml
https://github.com/terasolunaorg/terasoluna-tourreservation/issues/354
jdbc postgresql version up 9.4-1206-jdbc41
cherry-pick c52ada911e7b9698b4726f4710b22027e542251b
=> jdbc postgresql version up 9.4-1206-jdbc41 5.0.x

terasoluna-tourreservation-env/configs/tomcat-postgresql/resources/META-INF/spring/terasoluna-tourreservation-env.xml, terasoluna-tourreservation-env/configs/tomcat8-postgresql/resources/META-INF/spring/terasoluna-tourreservation-env.xml
Please review terasolunaorg/terasoluna-tourreservation#361
=> Fix terasoluna-tourreservation-env.xml #361

terasoluna-tourreservation-domain/pom.xml, terasoluna-tourreservation-domain/src/main/resources/META-INF/mybatis/mybatis-config.xml
Please review [#360](https://github.com/terasolunaorg/terasoluna-tourreservation/issues/360) .
=> add settings for using CGLIB in MyBatis proxyFactory. issues:#360

terasoluna-tourreservation-domain/pom.xml, terasoluna-tourreservation-domain/src/main/resources/META-INF/mybatis/mybatis-config.xml
Please review [#360](https://github.com/terasolunaorg/terasoluna-tourreservation/issues/360) again .
=> remove cglib dependency. issues:#360

.travis.yml
Please review terasolunaorg/terasoluna-tourreservation#375
=> fix travis.yml #375

terasoluna-tourreservation-domain/pom.xml, terasoluna-tourreservation-env/pom.xml, terasoluna-tourreservation-initdb/pom.xml, terasoluna-tourreservation-parent/pom.xml, terasoluna-tourreservation-selenium/pom.xml, terasoluna-tourreservation-web/pom.xml
Please review terasolunaorg/terasoluna-tourreservation#368
=> Update to 5.0.3-SNAPSHOT #368

pom.xml, terasoluna-tourreservation-domain/pom.xml, terasoluna-tourreservation-env/pom.xml, terasoluna-tourreservation-initdb/pom.xml, terasoluna-tourreservation-selenium/pom.xml, terasoluna-tourreservation-web/pom.xml
Please review terasolunaorg/terasoluna-tourreservation#369
=> Update to 5.1.1-SNAPSHOT #369

pom.xml, terasoluna-tourreservation-domain/pom.xml, terasoluna-tourreservation-env/pom.xml, terasoluna-tourreservation-initdb/pom.xml, terasoluna-tourreservation-selenium/pom.xml, terasoluna-tourreservation-web/pom.xml
Please review terasolunaorg/terasoluna-tourreservation#370
=> Update to 5.2.0-SNAPSHOT #370

README.md
Please review terasolunaorg/terasoluna-tourreservation#364
=> [5.1.x] Add travis-ci badge for 5.1.x on README.md #364

README.md
Please review terasolunaorg/terasoluna-tourreservation#364
=> Add travis-ci badge for 5.1.x on README.md #364

terasoluna-tourreservation-web/pom.xml
Please review https://github.com/terasolunaorg/terasoluna-tourreservation/issues/379.
=> add a dependency to taglibs-standard-jstlel #379

terasoluna-tourreservation-domain/pom.xml, terasoluna-tourreservation-env/pom.xml
Please review [#387](https://github.com/terasolunaorg/terasoluna-tourreservation/issues/387)
=> Add the type in the description of the dependency 'myBatis3' #387

eclipse/formatter.xml, pom.xml, terasoluna-tourreservation-domain/pom.xml, terasoluna-tourreservation-env/pom.xml, terasoluna-tourreservation-selenium/pom.xml, terasoluna-tourreservation-web/pom.xml
=> apply new pom structure #391

terasoluna-tourreservation-web/pom.xml
Please review #391.
(cherry picked from commit f169b357ded768dec722ed352a663edee22a1c2a)
=> add gfw-web-dependencies #391

terasoluna-tourreservation-web/src/main/resources/META-INF/spring/spring-mvc.xml
Please review https://github.com/terasolunaorg/terasoluna-tourreservation/issues/394.
(cherry picked from commit 4505cc044e734d4c3b995f51b190e620aecea328)
=> add wordarround to CVE-2016-5007 #394

terasoluna-tourreservation-web/src/main/resources/META-INF/spring/spring-mvc.xml
Please review https://github.com/terasolunaorg/terasoluna-tourreservation/issues/394.
(cherry picked from commit 4505cc044e734d4c3b995f51b190e620aecea328)
(cherry picked from commit 08238a79c5fb06a8b2bfd380db59718c6d468dbd)
=> [5.1.x] add wordarround to CVE-2016-5007 #394

terasoluna-tourreservation-web/src/main/resources/META-INF/spring/spring-mvc.xml
Please review https://github.com/terasolunaorg/terasoluna-tourreservation/issues/394.
(cherry picked from commit 4505cc044e734d4c3b995f51b190e620aecea328)
Conflicts:
terasoluna-tourreservation-web/src/main/resources/META-INF/spring/spring-mvc.xml
(cherry picked from commit d109ac579e1aa4a7e5c443148a122ceaceffcf60)
=> [5.0.x] add wordarround to CVE-2016-5007 #394

terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/LogInLogOutTest.java, terasoluna-tourreservation-web/src/main/webapp/WEB-INF/views/login/form.jsp
Please review https://github.com/terasolunaorg/terasoluna-tourreservation/issues/395
=> Remove Authentication failure-url mybatis3 Test #395

terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/LogInLogOutTest.java, terasoluna-tourreservation-web/src/main/webapp/WEB-INF/views/login/form.jsp
Please review https://github.com/terasolunaorg/terasoluna-tourreservation/issues/395
=> Remove failure-url mybatis3 Test For 5.1.1 #395

pom.xml, terasoluna-tourreservation-domain/pom.xml, terasoluna-tourreservation-env/pom.xml, terasoluna-tourreservation-initdb/pom.xml, terasoluna-tourreservation-selenium/pom.xml, terasoluna-tourreservation-web/pom.xml
Please review terasolunaorg/terasoluna-tourreservation#405
(cherry picked from commit 3f6a33a2b64b26e28b45eb6139f1073494be77d6)
=> update to 5.3.0-SNAPSHOT #405

.travis.yml, pom.xml, terasoluna-tourreservation-domain/pom.xml, terasoluna-tourreservation-env/pom.xml, terasoluna-tourreservation-initdb/pom.xml, terasoluna-tourreservation-selenium/pom.xml, terasoluna-tourreservation-web/pom.xml
Please review terasolunaorg/terasoluna-tourreservation#405
=>  update to 5.2.1-SNAPSHOT #405 

pom.xml, terasoluna-tourreservation-domain/pom.xml, terasoluna-tourreservation-env/pom.xml, terasoluna-tourreservation-initdb/pom.xml, terasoluna-tourreservation-selenium/pom.xml, terasoluna-tourreservation-web/pom.xml
Please review terasolunaorg/terasoluna-tourreservation#405
(cherry picked from commit 3e9c57616e6cada2cc2ad5160a985ab583f0db5f)
=> update to 5.1.2-SNAPSHOT #405

README.md
Please review terasolunaorg/terasoluna-tourreservation#406
(chrerry picked from commit 8a9326dbc64304b57c23330544deace5694ffe44)
=> [5.2.x] Add travis-ci badge for 5.2.x on README.md #406

README.md
Please review terasolunaorg/terasoluna-tourreservation#406
=> Add travis-ci badge for 5.2.x on README.md #406

pom.xml, terasoluna-tourreservation-web/src/main/java/org/terasoluna/tourreservation/app/login/LoginController.java, terasoluna-tourreservation-web/src/main/resources/META-INF/spring/spring-mvc.xml, terasoluna-tourreservation-web/src/main/resources/META-INF/spring/spring-security.xml, terasoluna-tourreservation-web/src/main/webapp/WEB-INF/web.xml
Please review https://github.com/terasolunaorg/terasoluna-tourreservation/issues/416 https://github.com/terasolunaorg/terasoluna-tourreservation/issues/418 .
=> Apply Spring IO Platform Athens-SR1 #416 #418

terasoluna-tourreservation-domain/src/test/java/org/terasoluna/tourreservation/domain/repository/reserve/ReserveRepositoryImplTest.java, terasoluna-tourreservation-domain/src/test/java/org/terasoluna/tourreservation/domain/repository/tourinfo/TourInfoRepositoryImplTest.java
Please review terasolunaorg/terasoluna-tourreservation#419.
(cherry picked from commit c05da1e4716b70d67b602c30d1c6e859ce14e501)
=> deleted deprecated API used in Test Case class. terasolunaorg/terasoluna-tourreservation#419

pom.xml
Please review terasolunaorg/terasoluna-tourreservation#421
=> update postgresql jdbc driver version mybatis3. #421

pom.xml
Please review terasolunaorg/terasoluna-tourreservation#421.
=> update postgresql jdbc driver version 5.2.x mybatis3. #421

pom.xml
Please review terasolunaorg/terasoluna-tourreservation#421.
=> update postgresql jdbc driver version 5.1.x mybatis3. #421

terasoluna-tourreservation-parent/pom.xml
Please review terasolunaorg/terasoluna-tourreservation#421.
=> update postgresql jdbc driver version 5.0.x mybatis3. #421 

terasoluna-tourreservation-web/src/main/java/org/terasoluna/tourreservation/app/error/ErrorController.java, terasoluna-tourreservation-web/src/main/resources/META-INF/spring/spring-security.xml, terasoluna-tourreservation-web/src/main/webapp/WEB-INF/web.xml
(cherry picked from commit c01d24495ec7653d4c8e020b0e0c41e5b3791eb1)
Please review terasolunaorg/terasoluna-tourreservation#418.
=> added error controller. terasolunaorg/terasoluna-tourreservation#418

terasoluna-tourreservation-domain/src/main/resources/META-INF/mybatis/mybatis-config.xml
Please review https://github.com/terasolunaorg/terasoluna-tourreservation/issues/436 .
=> remove <setting name="aggressiveLazyLoading" value="false" /> in mybatis/mybatis-config.xml

.travis.yml, terasoluna-tourreservation-parent/pom.xml
@kazuki43zoo 
Sorry, I had forgotten. Please review and merge https://github.com/terasolunaorg/terasoluna-tourreservation/issues/432 .
PR for JPA version is https://github.com/terasolunaorg/terasoluna-tourreservation/pull/434 .
(cherry picked from commit eed64fdf2bfae21638ae9a4762096dabc2eda4a9)
=> [5.0.x][MyBatis3] change java-version -> 1.8 #432

terasoluna-tourreservation-domain/src/main/resources/META-INF/spring/tourreservation-infra.xml, terasoluna-tourreservation-env/configs/tomcat-postgresql/resources/META-INF/spring/terasoluna-tourreservation-env.xml, terasoluna-tourreservation-env/configs/tomcat8-postgresql/resources/META-INF/spring/terasoluna-tourreservation-env.xml, terasoluna-tourreservation-env/src/main/resources/META-INF/spring/terasoluna-tourreservation-env.xml
please review https://github.com/terasolunaorg/terasoluna-tourreservation/issues/433.
=> [5.3.x]add settings that DataSourceTransactionManager#setRollbackOnCommitFaillure=true in xml files what using DataSourceTransactionManager

terasoluna-tourreservation-env/configs/tomcat-postgresql/ContainerConfigXML/context.xml, terasoluna-tourreservation-env/configs/tomcat-postgresql/ContainerConfigXML/context.xml.env.ftl, terasoluna-tourreservation-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml, terasoluna-tourreservation-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml.env.ftl
(cherry picked from commit 71e43043fae95c20068a980df940ff9e5f280f02)
Please review terasolunaorg/terasoluna-tourreservation#438.
=> Set defaultAutoCommit to false in context.xml terasolunaorg/terasoluna-tourreservation#438

terasoluna-tourreservation-env/configs/tomcat-postgresql/ContainerConfigXML/context.xml, terasoluna-tourreservation-env/configs/tomcat-postgresql/ContainerConfigXML/context.xml.env.ftl, terasoluna-tourreservation-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml, terasoluna-tourreservation-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml.env.ftl
(cherry picked from commit 71e43043fae95c20068a980df940ff9e5f280f02)
(cherry picked from commit e77b8106bf4fb8f14840e0efc2e399cca039647c)
Please review terasolunaorg/terasoluna-tourreservation#438.
=> [5.2.x] Set defaultAutoCommit to false in context.xml terasolunaorg/terasoluna-tourreservation#438

terasoluna-tourreservation-env/configs/tomcat-postgresql/ContainerConfigXML/context.xml, terasoluna-tourreservation-env/configs/tomcat-postgresql/ContainerConfigXML/context.xml.env.ftl, terasoluna-tourreservation-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml, terasoluna-tourreservation-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml.env.ftl
(cherry picked from commit 71e43043fae95c20068a980df940ff9e5f280f02)
(cherry picked from commit e77b8106bf4fb8f14840e0efc2e399cca039647c)
Please review terasolunaorg/terasoluna-tourreservation#438.
=> [5.1.x] Set defaultAutoCommit to false in context.xml terasolunaorg/terasoluna-tourreservation#438

terasoluna-tourreservation-env/configs/tomcat-postgresql/ContainerConfigXML/context.xml, terasoluna-tourreservation-env/configs/tomcat-postgresql/ContainerConfigXML/context.xml.env.ftl, terasoluna-tourreservation-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml, terasoluna-tourreservation-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml.env.ftl
(cherry picked from commit 71e43043fae95c20068a980df940ff9e5f280f02)
(cherry picked from commit e77b8106bf4fb8f14840e0efc2e399cca039647c)
Please review terasolunaorg/terasoluna-tourreservation#438.
=> [5.0.x] Set defaultAutoCommit to false in context.xml terasolunaorg/terasoluna-tourreservation#438

terasoluna-tourreservation-domain/src/main/resources/META-INF/spring/tourreservation-infra.xml, terasoluna-tourreservation-env/configs/tomcat-postgresql/resources/META-INF/spring/terasoluna-tourreservation-env.xml, terasoluna-tourreservation-env/configs/tomcat8-postgresql/resources/META-INF/spring/terasoluna-tourreservation-env.xml, terasoluna-tourreservation-env/src/main/resources/META-INF/spring/terasoluna-tourreservation-env.xml
please review terasolunaorg/terasoluna-tourreservation#433.
PR #147 の5.2.x版バックポートです。
=> [5.2.x]add settings that DataSourceTransactionManager#setRollbackOnCommitFaillure=true in xml files what using DataSourceTransactionManager.

pom.xml
please review https://github.com/terasolunaorg/terasoluna-tourreservation/issues/437
=> Modified /pom.xml for Maven Central.437

terasoluna-tourreservation-web/src/main/resources/META-INF/spring/spring-mvc.xml
=> Add excludedExceptions #445

terasoluna-tourreservation-web/src/main/resources/META-INF/spring/spring-mvc.xml
Please review terasolunaorg/terasoluna-tourreservation#420
=> Modify typo (workarround -> workaround) #420

terasoluna-tourreservation-web/src/main/resources/META-INF/spring/spring-mvc.xml
Please review terasolunaorg/terasoluna-tourreservation#420
=> [5.2.x] Modify typo (workarround -> workaround) #420

terasoluna-tourreservation-web/src/main/resources/META-INF/spring/spring-mvc.xml
Please review terasolunaorg/terasoluna-tourreservation#420
=> [5.1.x] Modify typo (workarround -> workaround) #420

terasoluna-tourreservation-web/src/main/resources/META-INF/spring/spring-mvc.xml
Please review terasolunaorg/terasoluna-tourreservation#420
=> [5.0.x] Modify typo (workarround -> workaround) #420

terasoluna-tourreservation-web/src/main/java/org/terasoluna/tourreservation/app/managereservation/ManageReservationController.java, terasoluna-tourreservation-web/src/main/java/org/terasoluna/tourreservation/app/reservetour/ReserveTourController.java, terasoluna-tourreservation-web/src/main/resources/META-INF/spring/spring-mvc.xml, terasoluna-tourreservation-web/src/main/resources/META-INF/spring/spring-security.xml, terasoluna-tourreservation-web/src/main/webapp/WEB-INF/views/common/top.jsp, terasoluna-tourreservation-web/src/main/webapp/WEB-INF/views/login/form.jsp, terasoluna-tourreservation-web/src/main/webapp/WEB-INF/views/menu/menu.jsp, terasoluna-tourreservation-web/src/main/webapp/WEB-INF/views/reservetour/reserveForm.jsp, terasoluna-tourreservation-web/src/main/webapp/WEB-INF/views/searchtour/searchForm.jsp, terasoluna-tourreservation-web/src/test/java/org/terasoluna/tourreservation/app/managereservation/ManageReservationControllerTest.java, terasoluna-tourreservation-web/src/test/java/org/terasoluna/tourreservation/app/reservetour/ReserveTourControllerTest.java
Please review terasolunaorg/terasoluna-tourreservation#453
(cherry picked from commit c8c77a98bca920e9316d5d16a559ec222a9f7b86)
=> [5.2.x] Apply changes of Spring Security 4 terasolunaorg/terasoluna-tourreservation#453

terasoluna-tourreservation-web/src/main/java/org/terasoluna/tourreservation/app/managereservation/ManageReservationController.java, terasoluna-tourreservation-web/src/main/java/org/terasoluna/tourreservation/app/reservetour/ReserveTourController.java, terasoluna-tourreservation-web/src/main/resources/META-INF/spring/spring-mvc.xml, terasoluna-tourreservation-web/src/main/resources/META-INF/spring/spring-security.xml, terasoluna-tourreservation-web/src/main/webapp/WEB-INF/views/common/top.jsp, terasoluna-tourreservation-web/src/main/webapp/WEB-INF/views/login/form.jsp, terasoluna-tourreservation-web/src/main/webapp/WEB-INF/views/menu/menu.jsp, terasoluna-tourreservation-web/src/main/webapp/WEB-INF/views/reservetour/reserveForm.jsp, terasoluna-tourreservation-web/src/main/webapp/WEB-INF/views/searchtour/searchForm.jsp, terasoluna-tourreservation-web/src/test/java/org/terasoluna/tourreservation/app/managereservation/ManageReservationControllerTest.java, terasoluna-tourreservation-web/src/test/java/org/terasoluna/tourreservation/app/reservetour/ReserveTourControllerTest.java
Please review terasolunaorg/terasoluna-tourreservation#453
(cherry picked from commit c8c77a98bca920e9316d5d16a559ec222a9f7b86)
=> [5.1.x] Apply changes of Spring Security 4 terasolunaorg/terasoluna-tourreservation#453

terasoluna-tourreservation-web/src/main/java/org/terasoluna/tourreservation/app/managereservation/ManageReservationController.java, terasoluna-tourreservation-web/src/main/java/org/terasoluna/tourreservation/app/reservetour/ReserveTourController.java, terasoluna-tourreservation-web/src/main/resources/META-INF/spring/spring-mvc.xml, terasoluna-tourreservation-web/src/main/resources/META-INF/spring/spring-security.xml, terasoluna-tourreservation-web/src/main/webapp/WEB-INF/views/common/top.jsp, terasoluna-tourreservation-web/src/main/webapp/WEB-INF/views/login/form.jsp, terasoluna-tourreservation-web/src/main/webapp/WEB-INF/views/menu/menu.jsp, terasoluna-tourreservation-web/src/main/webapp/WEB-INF/views/reservetour/reserveForm.jsp, terasoluna-tourreservation-web/src/main/webapp/WEB-INF/views/searchtour/searchForm.jsp, terasoluna-tourreservation-web/src/test/java/org/terasoluna/tourreservation/app/managereservation/ManageReservationControllerTest.java, terasoluna-tourreservation-web/src/test/java/org/terasoluna/tourreservation/app/reservetour/ReserveTourControllerTest.java
Please review terasolunaorg/terasoluna-tourreservation#453
=> Apply changes of Spring Security 4 terasolunaorg/terasoluna-tourreservation#453

terasoluna-tourreservation-env/configs/tomcat-postgresql/ContainerConfigXML/context.xml, terasoluna-tourreservation-env/configs/tomcat-postgresql/ContainerConfigXML/context.xml.env.ftl, terasoluna-tourreservation-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml, terasoluna-tourreservation-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml.env.ftl
Reverts terasolunaorg/terasoluna-tourreservation-mybatis3#149
See terasolunaorg/terasoluna-tourreservation#438
=> Revert "Set defaultAutoCommit to false in context.xml terasolunaorg/terasoluna-tourreservation#438"

terasoluna-tourreservation-env/configs/tomcat-postgresql/ContainerConfigXML/context.xml, terasoluna-tourreservation-env/configs/tomcat-postgresql/ContainerConfigXML/context.xml.env.ftl, terasoluna-tourreservation-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml, terasoluna-tourreservation-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml.env.ftl
Reverts terasolunaorg/terasoluna-tourreservation-mybatis3#150
See terasolunaorg/terasoluna-tourreservation#438
=> Revert "[5.2.x] Set defaultAutoCommit to false in context.xml terasolunaorg/terasoluna-tourreservation#438"

terasoluna-tourreservation-env/configs/tomcat-postgresql/ContainerConfigXML/context.xml, terasoluna-tourreservation-env/configs/tomcat-postgresql/ContainerConfigXML/context.xml.env.ftl, terasoluna-tourreservation-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml, terasoluna-tourreservation-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml.env.ftl
Reverts terasolunaorg/terasoluna-tourreservation-mybatis3#151
See terasolunaorg/terasoluna-tourreservation#438
=> Revert "[5.1.x] Set defaultAutoCommit to false in context.xml terasolunaorg/terasoluna-tourreservation#438"

terasoluna-tourreservation-env/configs/tomcat-postgresql/ContainerConfigXML/context.xml, terasoluna-tourreservation-env/configs/tomcat-postgresql/ContainerConfigXML/context.xml.env.ftl, terasoluna-tourreservation-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml, terasoluna-tourreservation-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml.env.ftl
Reverts terasolunaorg/terasoluna-tourreservation-mybatis3#152
See terasolunaorg/terasoluna-tourreservation#438
=> Revert "[5.0.x] Set defaultAutoCommit to false in context.xml terasolunaorg/terasoluna-tourreservation#438"

pom.xml, terasoluna-tourreservation-domain/pom.xml, terasoluna-tourreservation-env/pom.xml, terasoluna-tourreservation-initdb/pom.xml, terasoluna-tourreservation-selenium/pom.xml, terasoluna-tourreservation-web/pom.xml
Please review terasolunaorg/terasoluna-tourreservation#474.
=> [master]Update version to 5.4.0-SNAPSHOT.#474

pom.xml, terasoluna-tourreservation-domain/pom.xml, terasoluna-tourreservation-env/pom.xml, terasoluna-tourreservation-initdb/pom.xml, terasoluna-tourreservation-selenium/pom.xml, terasoluna-tourreservation-web/pom.xml
Please review terasolunaorg/terasoluna-tourreservation#474.
=> [5.3.x]Update version to 5.3.1-SNAPSHOT.#474

pom.xml, terasoluna-tourreservation-domain/pom.xml, terasoluna-tourreservation-env/pom.xml, terasoluna-tourreservation-initdb/pom.xml, terasoluna-tourreservation-selenium/pom.xml, terasoluna-tourreservation-web/pom.xml
Please review https://github.com/terasolunaorg/terasoluna-tourreservation/issues/474.
=> [5.2.x]Update version to 5.2.2-SNAPSHOT.#474

README.md
Please review https://github.com/terasolunaorg/terasoluna-tourreservation/issues/481.
=> [master]Modify travis-ci badge in README.md.#481

README.md
Please review terasolunaorg/terasoluna-tourreservation#481.
=> [5.2.x]Remove travis-ci badge in README.md.#481

README.md
Please review terasolunaorg/terasoluna-tourreservation#481.
=> [5.1.x]Remove travis-ci badge in README.md.#481

README.md
Please review terasolunaorg/terasoluna-tourreservation#481.
=> [5.0.x]Remove travis-ci badge in README.md.#481

.travis.yml
Please review https://github.com/terasolunaorg/terasoluna-tourreservation/issues/475.
=> Change to use terasoluna-gfw 5.3.x branch at .travis of 5.3.x branch #475

README.md
Please review terasolunaorg/terasoluna-tourreservation#481.
=> [5.3.x]Add travis-ci badge for 5.3.x in README.md.#481

.travis.yml
This PR is backport for terasoluna-tourreservation-mybatis3(master)
=> add firefox version at .travis.yml #496

.travis.yml
This PR is backport for terasoluna-tourreservation-mybatis3(5.3.x)
=> [5.3.x] add firefox version at .travis.yml #496

.travis.yml
This PR is backport for terasoluna-tourreservation-mybatis3(5.2.x)
=> [5.2.x] add firefox version at .travis.yml #496

.travis.yml
This PR is backport for terasoluna-tourreservation-mybatis3(5.1.x)
=> [5.1.x] add firefox version at .travis.yml #496

.travis.yml
This PR is backport for terasoluna-tourreservation-mybatis3(5.0.x)
=> [5.0.x] add firefox version at .travis.yml #496

.travis.yml, pom.xml, terasoluna-tourreservation-domain/pom.xml, terasoluna-tourreservation-env/pom.xml, terasoluna-tourreservation-initdb/pom.xml, terasoluna-tourreservation-selenium/pom.xml, terasoluna-tourreservation-web/pom.xml
Please review　https://github.com/terasolunaorg/terasoluna-tourreservation/issues/494 .
This PR is sideport for terasoluna-tourreservation-mybatis3(5.0.x)
=> [5.0.x] Apply multiple module project to 5.0.x #494

terasoluna-tourreservation-web/src/main/resources/META-INF/spring/spring-mvc.xml
Please review terasolunaorg/terasoluna-tourreservation#510
=> Remove definition of trimTokens #510

terasoluna-tourreservation-web/src/main/resources/META-INF/spring/spring-mvc.xml
Please review terasolunaorg/terasoluna-tourreservation#510
=> [5.3.x] Remove definition of trimTokens #510

pom.xml, terasoluna-tourreservation-domain/pom.xml, terasoluna-tourreservation-env/pom.xml, terasoluna-tourreservation-initdb/pom.xml, terasoluna-tourreservation-selenium/pom.xml, terasoluna-tourreservation-web/pom.xml
please review  terasolunaorg/terasoluna-tourreservation/issues/524
=> [5.3.x] fix SNAPSHOT version in pom.xml #524

terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/common/FunctionTestSupport.java
please review terasolunaorg/terasoluna-tourreservation#522
=> add firefox preference setting of no proxy. #522

terasoluna-tourreservation-env/configs/tomcat85-postgresql/ContainerConfigXML/context.xml, terasoluna-tourreservation-env/configs/tomcat85-postgresql/ContainerConfigXML/context.xml.env.ftl, terasoluna-tourreservation-env/configs/tomcat85-postgresql/resources/META-INF/spring/terasoluna-tourreservation-codelist.properties, terasoluna-tourreservation-env/configs/tomcat85-postgresql/resources/META-INF/spring/terasoluna-tourreservation-env.xml, terasoluna-tourreservation-env/configs/tomcat85-postgresql/resources/META-INF/spring/terasoluna-tourreservation-infra.properties, terasoluna-tourreservation-env/configs/tomcat85-postgresql/resources/dozer.properties, terasoluna-tourreservation-env/configs/tomcat85-postgresql/resources/log4jdbc.properties, terasoluna-tourreservation-env/configs/tomcat85-postgresql/resources/logback.xml, terasoluna-tourreservation-env/pom.xml
please review terasolunaorg/terasoluna-tourreservation#523
=> add profile of tomcat8.5. #523

terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/common/FunctionTestSupport.java
(cherry picked from commit 366460d661f028ac384c1f64b9f17983244784fa)
Please review　https://github.com/terasolunaorg/terasoluna-tourreservation/issues/522.
This PR is backport for terasoluna-tourreservation-mybatis3(5.3.x)
=> [5.3.x] add firefox preference setting of no proxy. #522

terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/common/FunctionTestSupport.java
(cherry picked from commit 366460d661f028ac384c1f64b9f17983244784fa)
Please review　https://github.com/terasolunaorg/terasoluna-tourreservation/issues/522.
This PR is backport for terasoluna-tourreservation-mybatis3(5.2.x)
=> [5.2.x] add firefox preference setting of no proxy. #522

terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/common/FunctionTestSupport.java
(cherry picked from commit 366460d661f028ac384c1f64b9f17983244784fa)
Please review　https://github.com/terasolunaorg/terasoluna-tourreservation/issues/522.
This PR is backport for terasoluna-tourreservation-mybatis3(5.1.x)
=> [5.1.x] add firefox preference setting of no proxy. #522

terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/common/FunctionTestSupport.java
(cherry picked from commit 366460d661f028ac384c1f64b9f17983244784fa)
Please review　https://github.com/terasolunaorg/terasoluna-tourreservation/issues/522.
This PR is backport for terasoluna-tourreservation-mybatis3(5.0.x)
=> [5.0.x] add firefox preference setting of no proxy. #522

terasoluna-tourreservation-env/configs/tomcat-postgresql/resources/logback.xml, terasoluna-tourreservation-env/configs/tomcat8-postgresql/resources/logback.xml, terasoluna-tourreservation-env/configs/tomcat85-postgresql/resources/logback.xml, terasoluna-tourreservation-env/src/main/resources/logback.xml, terasoluna-tourreservation-selenium/src/test/resources/logback.xml
plz rv terasolunaorg/terasoluna-tourreservation#509.
=> [mybatis3/master] add doctype.#509

terasoluna-tourreservation-env/configs/tomcat-postgresql/resources/logback.xml, terasoluna-tourreservation-env/configs/tomcat8-postgresql/resources/logback.xml, terasoluna-tourreservation-env/src/main/resources/logback.xml, terasoluna-tourreservation-selenium/src/test/resources/logback.xml
(cherry picked from commit f1de93370893acf50b0ed02c87c9fc07e01a50d5)
plz rv terasolunaorg/terasoluna-tourreservation#509.
(tomcat 8.5 is not need for 5.3.x)
=> [mybatis3/5.3.x] add doctype.#509

pom.xml, terasoluna-tourreservation-domain/pom.xml, terasoluna-tourreservation-env/pom.xml, terasoluna-tourreservation-initdb/pom.xml, terasoluna-tourreservation-selenium/pom.xml, terasoluna-tourreservation-web/pom.xml
Please review https://github.com/terasolunaorg/terasoluna-tourreservation/issues/534.
=> update to 5.5.0-SNAPSHOT #534

README.md
Please review https://github.com/terasolunaorg/terasoluna-tourreservation/issues/533.
=> [5.4.x] change link to badge in README.md #533

.travis.yml
(cherry picked from commit 885c91dbf094c8d4f7acd93039ffbb62c5a0299c)
please review terasolunaorg/terasoluna-tourreservation#541
=> fixed travis.yml #541

.travis.yml
(cherry picked from commit 885c91dbf094c8d4f7acd93039ffbb62c5a0299c)
please review terasolunaorg/terasoluna-tourreservation#541
=> [5.4.x] fixed travis.yml #541

.travis.yml
(cherry picked from commit 885c91dbf094c8d4f7acd93039ffbb62c5a0299c)
please review terasolunaorg/terasoluna-tourreservation#541
=> [5.3.x] fixed travis.yml #541

.travis.yml
please check terasolunaorg/terasoluna-tourreservation#539
=> change GFW_BRANCH to 5.4.x #539

pom.xml, terasoluna-tourreservation-domain/pom.xml, terasoluna-tourreservation-env/pom.xml, terasoluna-tourreservation-initdb/pom.xml, terasoluna-tourreservation-selenium/pom.xml, terasoluna-tourreservation-web/pom.xml
please review https://github.com/terasolunaorg/terasoluna-tourreservation/issues/551
=> [5.4.x] update snapshot version to 5.4.2 #551

pom.xml, terasoluna-tourreservation-domain/pom.xml, terasoluna-tourreservation-env/pom.xml, terasoluna-tourreservation-initdb/pom.xml, terasoluna-tourreservation-selenium/pom.xml, terasoluna-tourreservation-web/pom.xml
please review https://github.com/terasolunaorg/terasoluna-tourreservation/issues/551
=> [5.3.x] update snapshot version to 5.3.3 #551

.travis.yml
Please review [#541](https://github.com/terasolunaorg/terasoluna-tourreservation/issues/541)
(cherry picked from commit [885c91d](https://github.com/terasolunaorg/terasoluna-tourreservation/commit/885c91dbf094c8d4f7acd93039ffbb62c5a0299c))
=> [5.2.x-mybatis3] fixed travis.yml #541

.travis.yml
Please review [#541](https://github.com/terasolunaorg/terasoluna-tourreservation/issues/541)
(cherry picked from commit [885c91d](https://github.com/terasolunaorg/terasoluna-tourreservation/commit/885c91dbf094c8d4f7acd93039ffbb62c5a0299c))
=> [5.1.x-mybatis3] fixed travis.yml #541

.travis.yml
Please review [#541](https://github.com/terasolunaorg/terasoluna-tourreservation/issues/541)
(cherry picked from commit [885c91d](https://github.com/terasolunaorg/terasoluna-tourreservation/commit/885c91dbf094c8d4f7acd93039ffbb62c5a0299c))
=> [5.0.x-mybatis3] fixed travis.yml #541

pom.xml
(cherry picked from commit 3a278fdccb4de94a38980f47aaaab3eb7170da0d)
please review https://github.com/terasolunaorg/terasoluna-tourreservation/issues/569
=> update postgresql driver #569

.travis.yml, pom.xml, terasoluna-tourreservation-domain/pom.xml, terasoluna-tourreservation-domain/src/main/resources/META-INF/dozer/domain-mapping.xml, terasoluna-tourreservation-domain/src/test/java/org/terasoluna/tourreservation/domain/repository/tourinfo/TourInfoRepositoryImplTest.java, terasoluna-tourreservation-domain/src/test/java/org/terasoluna/tourreservation/domain/service/reserve/ReserveServiceImplSecurityTest.java, terasoluna-tourreservation-domain/src/test/java/org/terasoluna/tourreservation/domain/service/reserve/ReserveServiceImplTest.java, terasoluna-tourreservation-domain/src/test/java/org/terasoluna/tourreservation/domain/service/tourinfo/TourInfoServiceImplTest.java, terasoluna-tourreservation-domain/src/test/resources/test-context.xml, terasoluna-tourreservation-env/pom.xml, terasoluna-tourreservation-initdb/pom.xml, terasoluna-tourreservation-selenium/pom.xml, terasoluna-tourreservation-web/pom.xml, terasoluna-tourreservation-web/src/main/resources/META-INF/spring/applicationContext.xml, terasoluna-tourreservation-web/src/main/resources/META-INF/spring/spring-mvc.xml, terasoluna-tourreservation-web/src/test/java/org/terasoluna/tourreservation/app/managecustomer/ManageCustomerControllerTest.java, terasoluna-tourreservation-web/src/test/java/org/terasoluna/tourreservation/app/managereservation/ManageReservationControllerTest.java, terasoluna-tourreservation-web/src/test/java/org/terasoluna/tourreservation/app/reservetour/ReserveTourControllerTest.java, terasoluna-tourreservation-web/src/test/java/org/terasoluna/tourreservation/app/reservetour/ReserveTourHelperTest.java, terasoluna-tourreservation-web/src/test/java/org/terasoluna/tourreservation/app/searchtour/SearchTourControllerTest.java
Please review 
terasolunaorg/terasoluna-tourreservation#567 terasolunaorg/terasoluna-tourreservation#577 
terasolunaorg/terasoluna-tourreservation#579 terasolunaorg/terasoluna-tourreservation#580 
terasolunaorg/terasoluna-tourreservation#581 terasolunaorg/terasoluna-tourreservation#582 .
Original PR
#229 
Overview
- terasolunaorg/terasoluna-tourreservation#567
update version 5.5.0-SNAPSHOT -> 5.5.0.RC2-SNAPSHOT
4f15c61fc732c6184802e8aed06ec78f9ac4f29a 
- terasolunaorg/terasoluna-tourreservation#577
modified to correspond to change of dozer specification
5e9c032f021f4fff4c8d0fc51a7e00edeb8252e4 
- terasolunaorg/terasoluna-tourreservation#579 
respond to change of improvement of Pageable
8b991ad7fe678b530dfbde8cdd3296cf87fb5be0
- terasolunaorg/terasoluna-tourreservation#580 
respond to …
=> update to 5.5.0.RC2-SNAPSHOT #567 #576 #577 #578 #579 #580 #581 #582 #584

terasoluna-tourreservation-selenium/src/test/resources/ValidationMessages_ja.properties
Please review [#560](https://github.com/terasolunaorg/terasoluna-tourreservation/issues/560).
=> delete extra message #560

terasoluna-tourreservation-selenium/src/test/resources/ValidationMessages_ja.properties
Please review [#559](https://github.com/terasolunaorg/terasoluna-tourreservation/issues/559).
=> fix property message #559

pom.xml, terasoluna-tourreservation-domain/src/main/java/org/terasoluna/tourreservation/domain/service/reserve/ReserveServiceImpl.java, terasoluna-tourreservation-domain/src/main/resources/META-INF/dozer/domain-mapping.xml, terasoluna-tourreservation-domain/src/test/java/org/terasoluna/tourreservation/domain/service/reserve/ReserveServiceImplTest.java, terasoluna-tourreservation-web/src/main/java/org/terasoluna/tourreservation/app/managecustomer/ManageCustomerController.java, terasoluna-tourreservation-web/src/main/java/org/terasoluna/tourreservation/app/managereservation/ManageReservationController.java, terasoluna-tourreservation-web/src/main/java/org/terasoluna/tourreservation/app/managereservation/ManageReservationHelper.java, terasoluna-tourreservation-web/src/main/java/org/terasoluna/tourreservation/app/reservetour/ReserveTourHelper.java, terasoluna-tourreservation-web/src/main/java/org/terasoluna/tourreservation/app/searchtour/SearchTourController.java, terasoluna-tourreservation-web/src/test/java/org/terasoluna/tourreservation/app/managecustomer/ManageCustomerControllerTest.java, terasoluna-tourreservation-web/src/test/java/org/terasoluna/tourreservation/app/managereservation/ManageReservationControllerTest.java, terasoluna-tourreservation-web/src/test/java/org/terasoluna/tourreservation/app/reservetour/ReserveTourHelperTest.java, terasoluna-tourreservation-web/src/test/java/org/terasoluna/tourreservation/app/searchtour/SearchTourControllerTest.java
please review https://github.com/terasolunaorg/terasoluna-tourreservation/issues/585 terasolunaorg/terasoluna-tourreservation#586
=> [Cairo-SR3]Change Lombok' version to 1.18.2 #585 [Dozer 6.4.1]Upgrade Dozer #586

pom.xml
please review https://github.com/terasolunaorg/terasoluna-tourreservation/issues/595
=> update ver postgresql #595

pom.xml
Please review terasolunaorg/terasoluna-tourreservation#585.
=> [Brussels-SR14]Change Lombok' version to 1.18.4 #585

terasoluna-tourreservation-web/src/main/resources/ValidationMessages_ja.properties
Please review terasolunaorg/terasoluna-tourreservation#605 .
=> correct wrong validation message #605

.travis.yml
(cherry picked from commit f9f6ec48112b7ba98390bf8c4512295cad1299de)
Please review terasolunaorg/terasoluna-tourreservation#602.
=> fix build profile of terasoluna-gfw #602

terasoluna-tourreservation-domain/src/main/resources/META-INF/spring/terasoluna-tourreservation-codelist.xml, terasoluna-tourreservation-web/src/main/resources/META-INF/spring/spring-mvc.xml
please review terasolunaorg/terasoluna-tourreservation#609
=> fix fallbackTo property to codelist difinition #609

pom.xml
(cherry picked from commit 78d4cf296c4a8ddcc3f7a89a4fc68ae66a689524)
please review https://github.com/terasolunaorg/terasoluna-tourreservation/issues/612
=> update jdbc driver #612

terasoluna-tourreservation-domain/src/main/java/org/terasoluna/tourreservation/domain/repository/age/AgeRepository.java, terasoluna-tourreservation-domain/src/main/java/org/terasoluna/tourreservation/domain/repository/customer/CustomerRepository.java, terasoluna-tourreservation-domain/src/main/java/org/terasoluna/tourreservation/domain/repository/reserve/ReserveRepository.java, terasoluna-tourreservation-domain/src/main/java/org/terasoluna/tourreservation/domain/service/customer/CustomerServiceImpl.java, terasoluna-tourreservation-domain/src/main/java/org/terasoluna/tourreservation/domain/service/reserve/AuthorizedReserveSharedServiceImpl.java, terasoluna-tourreservation-domain/src/main/java/org/terasoluna/tourreservation/domain/service/reserve/ReserveServiceImpl.java, terasoluna-tourreservation-domain/src/main/java/org/terasoluna/tourreservation/domain/service/tourinfo/PriceCalculateSharedServiceImpl.java, terasoluna-tourreservation-domain/src/main/java/org/terasoluna/tourreservation/domain/service/userdetails/ReservationUserDetailsService.java, terasoluna-tourreservation-domain/src/main/resources/org/terasoluna/tourreservation/domain/repository/age/AgeRepository.xml, terasoluna-tourreservation-domain/src/main/resources/org/terasoluna/tourreservation/domain/repository/customer/CustomerRepository.xml, terasoluna-tourreservation-domain/src/main/resources/org/terasoluna/tourreservation/domain/repository/reserve/ReserveRepository.xml, terasoluna-tourreservation-domain/src/test/java/org/terasoluna/tourreservation/domain/service/customer/CustomerServiceImplTest.java, terasoluna-tourreservation-domain/src/test/java/org/terasoluna/tourreservation/domain/service/reserve/ReserveServiceImplSecurityTest.java, terasoluna-tourreservation-domain/src/test/java/org/terasoluna/tourreservation/domain/service/reserve/ReserveServiceImplTest.java
please review terasolunaorg/terasoluna-tourreservation#578
=> findOne -> findById delete -> deleteById #578

terasoluna-tourreservation-web/pom.xml, terasoluna-tourreservation-web/src/test/java/org/terasoluna/tourreservation/app/reservetour/ReserveTourControllerTest.java
(cherry picked from commit 4e891c747a1bc25c8a5b907e8208ae2f83967cf2)
(cherry picked from commit 2ba563f486af123be884d107e709bf3a3711cc2f)
Please review terasolunaorg/terasoluna-tourreservation#584 .
This PR is backport for 5.4.x .
=> [5.4.x] use UserDetails at ReserveTourControllerTest #584

pom.xml, terasoluna-tourreservation-domain/pom.xml, terasoluna-tourreservation-env/pom.xml, terasoluna-tourreservation-initdb/pom.xml, terasoluna-tourreservation-selenium/pom.xml, terasoluna-tourreservation-web/pom.xml
please review https://github.com/terasolunaorg/terasoluna-tourreservation/issues/618
=> update to 5.6.0-SNAPSHOT #618

.travis.yml, pom.xml, terasoluna-tourreservation-domain/pom.xml, terasoluna-tourreservation-env/pom.xml, terasoluna-tourreservation-initdb/pom.xml, terasoluna-tourreservation-selenium/pom.xml, terasoluna-tourreservation-web/pom.xml
please review https://github.com/terasolunaorg/terasoluna-tourreservation/issues/618
=> update to 5.5.2-SNAPSHOT #618

terasoluna-tourreservation-domain/src/main/resources/META-INF/spring/terasoluna-tourreservation-codelist.xml, terasoluna-tourreservation-domain/src/main/resources/META-INF/spring/terasoluna-tourreservation-domain.xml, terasoluna-tourreservation-domain/src/main/resources/META-INF/spring/terasoluna-tourreservation-infra.xml, terasoluna-tourreservation-domain/src/main/resources/META-INF/spring/tourreservation-domain.xml, terasoluna-tourreservation-domain/src/main/resources/META-INF/spring/tourreservation-infra.xml, terasoluna-tourreservation-domain/src/test/resources/org/terasoluna/tourreservation/domain/service/reserve/ReserveServiceImplSecurityTest-context.xml, terasoluna-tourreservation-domain/src/test/resources/test-context.xml, terasoluna-tourreservation-env/configs/tomcat-postgresql/resources/META-INF/spring/terasoluna-tourreservation-env.xml, terasoluna-tourreservation-env/configs/tomcat8-postgresql/resources/META-INF/spring/terasoluna-tourreservation-env.xml, terasoluna-tourreservation-env/configs/tomcat85-postgresql/resources/META-INF/spring/terasoluna-tourreservation-env.xml, terasoluna-tourreservation-env/src/main/resources/META-INF/spring/terasoluna-tourreservation-env.xml, terasoluna-tourreservation-selenium/src/test/resources/META-INF/spring/seleniumContext.xml, terasoluna-tourreservation-web/src/main/resources/META-INF/spring/applicationContext.xml, terasoluna-tourreservation-web/src/main/resources/META-INF/spring/spring-mvc.xml, terasoluna-tourreservation-web/src/main/resources/META-INF/spring/spring-security.xml
Please review terasolunaorg/terasoluna-tourreservation#624.
=> [5.4.x] replace schema location for Spring from http to https #624

terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/common/FirefoxDriverFactoryBean.java, terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/common/FunctionTestSupport.java, terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/CustomerRegisterTest.java, terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/CustomerRegisterValidateTest.java, terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/LanguageSwitchTest.java, terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/LogInLogOutTest.java, terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/LogInReservUpdateTest.java, terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/SystemErrorTest.java, terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/TokenCheckErrorTest.java, terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/TourSearchPaginationTest.java, terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/TourSearchRegistValidateTest.java, terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/TourSearchValidateTest.java, terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/UnLogInTourSearchTest.java, terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/UnauthorizedAccessTest.java, terasoluna-tourreservation-selenium/src/test/resources/META-INF/spring/seleniumContext.xml
Please review terasolunaorg/terasoluna-tourreservation#573
Based on the following PR, I incorporated the correction not related to the Selenium update.
https://github.com/terasolunaorg/terasoluna-tourreservation-mybatis3/pull/247
=> udpate selenium backport #573

pom.xml, terasoluna-tourreservation-domain/pom.xml, terasoluna-tourreservation-web/src/main/resources/fonts/ipaexm00401/IPA_Font_License_Agreement_v1.0.txt, terasoluna-tourreservation-web/src/main/resources/fonts/ipaexm00401/fonts.xml, terasoluna-tourreservation-web/src/main/resources/jasperreports_extension.properties, terasoluna-tourreservation-web/src/main/webapp/WEB-INF/reports/reservationReportPdf.jrxml
(cherry picked from commit 671af429727638c8d0e78e9514952fd044e6ad58)
Please review terasolunaorg/terasoluna-tourreservation#630 and terasolunaorg/terasoluna-tourreservation#575 .
This PR is sideport for Mybatis3
=> Upgrade JasperReports #630 Support Linux Environment #575

.travis.yml
Please review terasolunaorg/terasoluna-tourreservation#638 terasolunaorg/terasoluna-tourreservation#639 terasolunaorg/terasoluna-tourreservation#641 terasolunaorg/terasoluna-tourreservation#643 .
=> Change Oracle JDK -> Open JDK #638 Adapt xvfb usage at Xenial environment #639 Suppress log output #641 Improvement Travis script #643

.travis.yml
(cherry picked from commit c4388ea5c4135a6c8d65ce213107f6b8e03a9313)
Please review terasolunaorg/terasoluna-tourreservation#640 .
=> Apply development/5.6.0 #640

terasoluna-tourreservation-domain/src/main/resources/META-INF/spring/terasoluna-tourreservation-codelist.xml, terasoluna-tourreservation-domain/src/main/resources/META-INF/spring/terasoluna-tourreservation-domain.xml, terasoluna-tourreservation-domain/src/main/resources/META-INF/spring/terasoluna-tourreservation-infra.xml, terasoluna-tourreservation-domain/src/main/resources/META-INF/spring/tourreservation-domain.xml, terasoluna-tourreservation-domain/src/main/resources/META-INF/spring/tourreservation-infra.xml, terasoluna-tourreservation-domain/src/test/resources/org/terasoluna/tourreservation/domain/service/reserve/ReserveServiceImplSecurityTest-context.xml, terasoluna-tourreservation-domain/src/test/resources/test-context.xml, terasoluna-tourreservation-env/configs/tomcat-postgresql/resources/META-INF/spring/terasoluna-tourreservation-env.xml, terasoluna-tourreservation-env/configs/tomcat8-postgresql/resources/META-INF/spring/terasoluna-tourreservation-env.xml, terasoluna-tourreservation-env/configs/tomcat85-postgresql/resources/META-INF/spring/terasoluna-tourreservation-env.xml, terasoluna-tourreservation-env/configs/tomcat9-postgresql/resources/META-INF/spring/terasoluna-tourreservation-env.xml, terasoluna-tourreservation-env/src/main/resources/META-INF/spring/terasoluna-tourreservation-env.xml, terasoluna-tourreservation-selenium/src/test/resources/META-INF/spring/seleniumContext.xml, terasoluna-tourreservation-web/src/main/resources/META-INF/spring/applicationContext.xml, terasoluna-tourreservation-web/src/main/resources/META-INF/spring/spring-mvc.xml, terasoluna-tourreservation-web/src/main/resources/META-INF/spring/spring-security.xml
Please review terasolunaorg/terasoluna-tourreservation/issues/624 .
Cherry picked from commit b367854 .
=> replace schema location for spring from http to https #624

.travis.yml
Please review  terasolunaorg/terasoluna-tourreservation#638  terasolunaorg/terasoluna-tourreservation#639  terasolunaorg/terasoluna-tourreservation#641  terasolunaorg/terasoluna-tourreservation#643 .
Cherry-pick from PR https://github.com/terasolunaorg/terasoluna-tourreservation/pull/647 .
=> [5.5.x] Change Oracle JDK -> Open JDK #638 Adapt xvfb usage at Xenial environment #639 Suppress log output #641 Improvement Travis script #643

.travis.yml
Cherry-pick from PR https://github.com/terasolunaorg/terasoluna-tourreservation/pull/648 .
=> [5.4.x] Suppress log output #641 Improvement Travis script #643 Fix Travis CI environment for Trusty #638

.travis.yml
Cherry-pick from PR terasolunaorg/terasoluna-tourreservation#649 .
=> [5.3.x] Suppress log output #641 Improvement Travis script #643 Fix Travis CI environment for Trusty #638

.travis.yml
Cherry-pick from PR terasolunaorg/terasoluna-tourreservation#650 .
=> [5.2.x] Suppress log output #641 Improvement Travis script #643 Fix Travis CI environment for Trusty #638

.travis.yml
Cherry-pick from PR https://github.com/terasolunaorg/terasoluna-tourreservation/pull/653 .
=> [5.1.x] Suppress log output #641 Improvement Travis script #643 Fix Travis CI environment for Trusty #638

.travis.yml
Cherry-pick from PR https://github.com/terasolunaorg/terasoluna-tourreservation/pull/652 .
=> [5.0.x] Suppress log output #641 Improvement Travis script #643 Fix Travis CI environment for Trusty #638

terasoluna-tourreservation-web/src/main/resources/ValidationMessages.properties
please review https://github.com/terasolunaorg/terasoluna-tourreservation/issues/654
=> remove validation messages #654

terasoluna-tourreservation-env/configs/tomcat-postgresql/resources/META-INF/spring/terasoluna-tourreservation-env.xml, terasoluna-tourreservation-env/configs/tomcat-postgresql/resources/log4jdbc.properties, terasoluna-tourreservation-env/configs/tomcat-postgresql/resources/logback.xml, terasoluna-tourreservation-env/configs/tomcat8-postgresql/resources/META-INF/spring/terasoluna-tourreservation-env.xml, terasoluna-tourreservation-env/configs/tomcat8-postgresql/resources/log4jdbc.properties, terasoluna-tourreservation-env/configs/tomcat85-postgresql/resources/META-INF/spring/terasoluna-tourreservation-env.xml, terasoluna-tourreservation-env/configs/tomcat85-postgresql/resources/log4jdbc.properties, terasoluna-tourreservation-env/configs/tomcat9-postgresql/resources/META-INF/spring/terasoluna-tourreservation-env.xml, terasoluna-tourreservation-env/configs/tomcat9-postgresql/resources/log4jdbc.properties, terasoluna-tourreservation-env/src/main/resources/META-INF/spring/terasoluna-tourreservation-env.xml, terasoluna-tourreservation-env/src/main/resources/log4jdbc.properties, terasoluna-tourreservation-env/src/main/resources/logback.xml
terasolunaorg/terasoluna-tourreservation#657
(cherry picked from commit 84c81122c618f811d3a561ec46498aca93b2c065)
=> remove log4jdbc-remix #657 (#658)

terasoluna-tourreservation-domain/src/test/java/org/terasoluna/tourreservation/domain/service/customer/CustomerServiceImplTest.java, terasoluna-tourreservation-domain/src/test/resources/test-context.xml, terasoluna-tourreservation-web/src/main/resources/META-INF/spring/applicationContext.xml
please review https://github.com/terasolunaorg/terasoluna-tourreservation/issues/660
cherry-pick https://github.com/terasolunaorg/terasoluna-tourreservation/pull/661 , https://github.com/terasolunaorg/terasoluna-tourreservation/pull/662
=> setting password encoder #660

pom.xml
please review https://github.com/terasolunaorg/terasoluna-tourreservation/issues/656
=> update JDBC Driver #656

terasoluna-tourreservation-web/pom.xml
pleaser review https://github.com/terasolunaorg/terasoluna-tourreservation/issues/664
(cherry picked from commit c73b3f6e6abfd2723ac8fd52e9c269bc46f3e7f8)
=> upgrade hamcrest to 2.x #664

pom.xml
(cherry picked from commit a171c44bd2be536fe9694b8300ad485d36c22e90)
please review https://github.com/terasolunaorg/terasoluna-tourreservation/issues/656
=> upgrade jdbc 42.2.9 #656

terasoluna-tourreservation-env/configs/tomcat-postgresql/resources/logback.xml, terasoluna-tourreservation-env/configs/tomcat8-postgresql/resources/logback.xml, terasoluna-tourreservation-env/configs/tomcat85-postgresql/resources/logback.xml, terasoluna-tourreservation-env/configs/tomcat9-postgresql/resources/logback.xml, terasoluna-tourreservation-env/src/main/resources/logback.xml
(cherry picked from commit db79aa623559247f7281421af35dfacab2d7b04b)
Please review terasolunaorg/terasoluna-tourreservation#657.
=> change loglevel of Repository to trace to log ResultSet #657

pom.xml, terasoluna-tourreservation-domain/pom.xml, terasoluna-tourreservation-env/pom.xml, terasoluna-tourreservation-initdb/pom.xml, terasoluna-tourreservation-selenium/pom.xml, terasoluna-tourreservation-web/pom.xml
(cherry picked from commit a90482e36f5ee795db5f93af88139ec5c5213166)
Please review terasolunaorg/terasoluna-tourreservation#679.
=> update 5.7.0-SNAPSHOT #679

README.md, pom.xml, terasoluna-tourreservation-domain/pom.xml, terasoluna-tourreservation-env/pom.xml, terasoluna-tourreservation-initdb/pom.xml, terasoluna-tourreservation-selenium/pom.xml, terasoluna-tourreservation-web/pom.xml
* update 5.6.1-SNAPSHOT #679
* fix travis url to 5.6.x #679
(cherry picked from commit 3b86d6f206a45fe0c9ba7a804f9a0a3068c27854)
Please review terasolunaorg/terasoluna-tourreservation#679.
=> update 5.6.1-SNAPSHOT #679

.travis.yml
(cherry picked from commit 433fa2e2af1b9482af7f8e063302575e23101aaf)
Please review https://github.com/terasolunaorg/terasoluna-tourreservation/issues/678
- When I checked the settings of travis.ci below, I confirmed that the correction was reflected.
https://travis-ci.org/github/terasolunaorg/terasoluna-tourreservation-mybatis3/builds/746672667/config
=> update postgre, firefox. #678

.travis.yml
(cherry picked from commit 0fcd994d004cdc2cdcd763d4aac1d4d492b1bea2)
Please review https://github.com/terasolunaorg/terasoluna-tourreservation/issues/678#issuecomment-747116810 .
=> setting param PGPORT. #678

.travis.yml
(cherry picked from commit 433fa2e2af1b9482af7f8e063302575e23101aaf)
(cherry picked from commit b115ee0ca88d3effc8864b12d4c237bce08d7e12)
Please review https://github.com/terasolunaorg/terasoluna-tourreservation/issues/689
- When I checked the settings of travis.ci below, I confirmed that the correction was reflected.
https://travis-ci.org/github/terasolunaorg/terasoluna-tourreservation-mybatis3/builds/746907782/config
=> [5.6.x]update postgresql, firefox in travis.yml #689

pom.xml, terasoluna-tourreservation-domain/pom.xml, terasoluna-tourreservation-env/pom.xml, terasoluna-tourreservation-initdb/pom.xml, terasoluna-tourreservation-selenium/pom.xml, terasoluna-tourreservation-web/pom.xml
(cherry picked from commit 5170a4380c5aa575a07ad5de28f11890b41383c9)
Please review https://github.com/terasolunaorg/terasoluna-tourreservation/issues/694
=> update 5.6.2-SNAPSHOT #694

pom.xml, terasoluna-tourreservation-domain/pom.xml, terasoluna-tourreservation-env/pom.xml, terasoluna-tourreservation-initdb/pom.xml, terasoluna-tourreservation-selenium/pom.xml, terasoluna-tourreservation-web/pom.xml
(cherry picked from commit 88de9ab63c41a2bf7f0b1ced3500bd33eb1ea7ff)
Please review https://github.com/terasolunaorg/terasoluna-tourreservation/issues/696
=> update 5.5.3-SNAPSHOT #696

pom.xml, terasoluna-tourreservation-domain/pom.xml, terasoluna-tourreservation-web/pom.xml
please review https://github.com/terasolunaorg/terasoluna-tourreservation/issues/692 .
=> depend jakarta lib. #692

pom.xml
(cherry picked from commit b7a8634a6465869d5020db8377b3d1deca1d7d97)
Please review https://github.com/terasolunaorg/terasoluna-tourreservation/issues/698
=> set source to maven-javadoc-plugin #698

pom.xml
(cherry picked from commit b7a8634a6465869d5020db8377b3d1deca1d7d97)
(cherry picked from commit 7d57e0f818fcd4f8c1f3910eafb0b7994a6ecb22)
Please review https://github.com/terasolunaorg/terasoluna-tourreservation/issues/701
=> [5.6.x] set source to maven-javadoc-plugin #698

.gitignore
(cherry picked from commit 929a84afe203ab58d180b1176bdca431cb2334ac)
Please Review https://github.com/terasolunaorg/terasoluna-tourreservation/issues/706 .
Removed unnecessary settings from gitignore.
=> Remove unnecessary settings from gitignore #706

pom.xml, terasoluna-tourreservation-domain/pom.xml, terasoluna-tourreservation-env/pom.xml, terasoluna-tourreservation-initdb/pom.xml, terasoluna-tourreservation-selenium/pom.xml, terasoluna-tourreservation-web/pom.xml
please review https://github.com/terasolunaorg/terasoluna-tourreservation/issues/710
=> update to 5.8.0-SNAPSHOT. #710

.travis.yml, README.md, pom.xml, terasoluna-tourreservation-domain/pom.xml, terasoluna-tourreservation-env/pom.xml, terasoluna-tourreservation-initdb/pom.xml, terasoluna-tourreservation-selenium/pom.xml, terasoluna-tourreservation-web/pom.xml
Please review https://github.com/terasolunaorg/terasoluna-tourreservation/issues/712
In .travis.yml, the cloned terasoluna-gfw was master, so it was fixed.
=> update to 5.6.3-SNAPSHOT. #712

pom.xml, terasoluna-tourreservation-domain/pom.xml, terasoluna-tourreservation-selenium/pom.xml, terasoluna-tourreservation-web/pom.xml
(cherry picked from commit f591f9daa35ae25255cfd22dd930bc52ed2703de)
Please review https://github.com/terasolunaorg/terasoluna-tourreservation/issues/686
See https://github.com/terasolunaorg/terasoluna-tourreservation/issues/686#issuecomment-891654903
Modified each pom.xml to match multi-blank.
=> aligned plugin settings to blank project #686

pom.xml
(cherry picked from commit aa028f5eee3473cec3862fe989181c4e563e88ed)
Please review https://github.com/terasolunaorg/terasoluna-tourreservation/issues/719
See https://github.com/terasolunaorg/terasoluna-tourreservation/issues/719#issuecomment-906922952
=> fix license-maven-plugin setteing #719

.travis.yml, pom.xml
Please review https://github.com/terasolunaorg/terasoluna-tourreservation/issues/726
=> [5.7.x] fix license-maven-plugin setteing #719

pom.xml
(cherry picked from commit b2601abc28f2883e4dd32315d2ccc5d6443e8fbb)
=> Match postgresql and ojdbc versions with Spring Boot #730

pom.xml
(cherry picked from commit b2601abc28f2883e4dd32315d2ccc5d6443e8fbb)
(cherry picked from commit 68895e0bba7f982cfd4ddfe6ea0125ea23b93b86)
terasolunaorg/terasoluna-tourreservation#732
=> Match postgresql and ojdbc versions with Spring Boot #730 #732

README.md, terasoluna-tourreservation-selenium/src/test/resources/wdm.properties
(cherry picked from commit b39dd6e00864aaa248241d70d4a96f5a19858a41)
terasolunaorg/terasoluna-tourreservation#736
=> geckodriver version upgrade #736

README.md, terasoluna-tourreservation-selenium/src/test/resources/wdm.properties
(cherry picked from commit b39dd6e00864aaa248241d70d4a96f5a19858a41)
(cherry picked from commit b11475c4a4f31fd9bdfa64fca344b5a0a5ba7d71)
terasolunaorg/terasoluna-tourreservation#738
=> geckodriver version upgrade #736 #738

terasoluna-tourreservation-env/configs/tomcat9-postgresql/resources/logback.xml, terasoluna-tourreservation-env/src/main/resources/logback.xml, terasoluna-tourreservation-selenium/src/test/resources/logback.xml
(cherry picked from commit b4b0b816725e430fa49de3616da6575a3f939330)
Please review https://github.com/terasolunaorg/terasoluna-tourreservation/issues/742
=> changed log format #742

README.md
Please review https://github.com/terasolunaorg/terasoluna-tourreservation/issues/748
=> remove build status. #748

README.md
Please review https://github.com/terasolunaorg/terasoluna-tourreservation/issues/750
=> remove build status. #750

pom.xml, terasoluna-tourreservation-domain/pom.xml, terasoluna-tourreservation-env/pom.xml, terasoluna-tourreservation-initdb/pom.xml, terasoluna-tourreservation-selenium/pom.xml, terasoluna-tourreservation-web/pom.xml
Please review https://github.com/terasolunaorg/terasoluna-tourreservation/issues/756
=> update SNAPSHOT to 5.7.2 #756

.github/PULL_REQUEST_TEMPLATE.md
Please review terasolunaorg/terasoluna-tourreservation#758
=> created pull request template #758

terasoluna-tourreservation-web/src/main/webapp/WEB-INF/views/managereservation/updateConfirm.jsp
Please review https://github.com/terasolunaorg/terasoluna-tourreservation/issues/555
=> issue 555  reverse companyName and paymentCompanyname(PR redo)

terasoluna-tourreservation-web/src/main/java/org/terasoluna/tourreservation/app/managecustomer/CustomerForm.java
Please review  terasolunaorg/terasoluna-tourreservation#558
Sideport to terasoluna-tourreservation-mybatis3
Sideport operation log:
git cherry-pick -x 3abff48bfac3dfe554096370c0cce352f374909f
=> Sideport:Issue/558 upper limit check
